name = "wedding-kenmiki"
compatibility_date = "2024-12-01"

[[r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "kenmiki-wedding-photo"

[[r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "kenmiki-wedding-assets"
